/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AKBAR
 */
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
public class ListSetMap extends javax.swing.JFrame {
    DefaultListModel<String> dlm;
    List<String> itemsList = new ArrayList<>();
    Set<String> itemsSet = new HashSet<>();
    Map<Integer, String> itemsMap = new HashMap<>();

    /**
     * Creates new form ListSetMap
     */
    public ListSetMap() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jListItem.setModel(dlm);
        updateLabelList();
        updateLabelSet();
        updateLabelMap();
    }
    
    private void updateLabelList() {
        jLabelJumlahList.setText("Data tersimpan = " + itemsList.size());
    }
    private void updateLabelSet() {
        jLabelJumlahSet.setText("Data tersimpan = " + itemsSet.size());
    }
    private void updateLabelMap() {
        jLabelJumlahMap.setText("Data tersimpan = " + itemsMap.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        ButtonClearAll = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        jLabelItemName = new javax.swing.JLabel();
        TextFieldItemName = new javax.swing.JTextField();
        ButtonSaveToList = new javax.swing.JButton();
        ButtonInsertDataList = new javax.swing.JButton();
        ButtonSaveToSet = new javax.swing.JButton();
        ButtonInsertDataSet = new javax.swing.JButton();
        ButtonSaveToMap = new javax.swing.JButton();
        ButtonInsertDataMap = new javax.swing.JButton();
        jLabelJumlahList = new javax.swing.JLabel();
        jLabelJumlahSet = new javax.swing.JLabel();
        jLabelJumlahMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        ButtonClearAll.setText("CLEAR ALL");
        ButtonClearAll.addActionListener(this::ButtonClearAllActionPerformed);

        ButtonAdd.setText("ADD");
        ButtonAdd.addActionListener(this::ButtonAddActionPerformed);

        ButtonUpdate.setText("UPDATE");
        ButtonUpdate.addActionListener(this::ButtonUpdateActionPerformed);

        ButtonDelete.setText("DELETE");
        ButtonDelete.addActionListener(this::ButtonDeleteActionPerformed);

        jLabelItemName.setText("Item Name :");

        ButtonSaveToList.setText("Save to List");
        ButtonSaveToList.addActionListener(this::ButtonSaveToListActionPerformed);

        ButtonInsertDataList.setText("Insert Data List");
        ButtonInsertDataList.addActionListener(this::ButtonInsertDataListActionPerformed);

        ButtonSaveToSet.setText("Save to Set");
        ButtonSaveToSet.addActionListener(this::ButtonSaveToSetActionPerformed);

        ButtonInsertDataSet.setText("Insert Data Set");
        ButtonInsertDataSet.addActionListener(this::ButtonInsertDataSetActionPerformed);

        ButtonSaveToMap.setText("Save to Map");
        ButtonSaveToMap.addActionListener(this::ButtonSaveToMapActionPerformed);

        ButtonInsertDataMap.setText("Insert Data Map");
        ButtonInsertDataMap.addActionListener(this::ButtonInsertDataMapActionPerformed);

        jLabelJumlahList.setText("Data tersimpan = 0");

        jLabelJumlahSet.setText("Data tersimpan = 0");

        jLabelJumlahMap.setText("Data tersimpan = 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(ButtonClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonDelete)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonInsertDataMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSaveToMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonInsertDataSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSaveToList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonInsertDataList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSaveToSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJumlahSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJumlahList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJumlahMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSaveToList)
                            .addComponent(jLabelJumlahList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonInsertDataList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSaveToSet)
                            .addComponent(jLabelJumlahSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonInsertDataSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSaveToMap)
                            .addComponent(jLabelJumlahMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonInsertDataMap)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAdd)
                    .addComponent(ButtonUpdate)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonClearAll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveToListActionPerformed
        // TODO add your handling code here:
        if (!itemsList.isEmpty()) {
            itemsList.clear();
        }
        for (int i = 0; i < dlm.getSize(); i++) {
            itemsList.add(dlm.getElementAt(i));
        }
        updateLabelList();
    }//GEN-LAST:event_ButtonSaveToListActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        // TODO add your handling code here:
        if (!TextFieldItemName.getText().isEmpty()) {
            dlm.addElement(TextFieldItemName.getText());
            TextFieldItemName.setText("");
        }
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex();
        if (index != -1 && !TextFieldItemName.getText().isEmpty()) {
            String selected = TextFieldItemName.getText();
            dlm.setElementAt(selected, index);
            TextFieldItemName.setText("");
        }
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex();
        if (index != -1) {
            dlm.removeElementAt(index);
            TextFieldItemName.setText("");
        }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearAllActionPerformed
        // TODO add your handling code here:
        dlm.clear();
    }//GEN-LAST:event_ButtonClearAllActionPerformed

    private void ButtonSaveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveToSetActionPerformed
        // TODO add your handling code here:
        if (!itemsSet.isEmpty()) {
            itemsSet.clear();
        }
        for (int i = 0; i < dlm.getSize(); i++) {
            itemsSet.add(dlm.getElementAt(i));
        }
        updateLabelSet();
    }//GEN-LAST:event_ButtonSaveToSetActionPerformed

    private void ButtonInsertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertDataListActionPerformed
        // TODO add your handling code here:
        for (String item : itemsList) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_ButtonInsertDataListActionPerformed

    private void ButtonInsertDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertDataSetActionPerformed
        // TODO add your handling code here:
        for (String item : itemsSet) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_ButtonInsertDataSetActionPerformed

    private void ButtonSaveToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveToMapActionPerformed
        // TODO add your handling code here:
        if (!itemsMap.isEmpty()) {
            itemsMap.clear();
        }
        for (int i = 0; i < dlm.getSize(); i++) {
            itemsMap.put(i, dlm.getElementAt(i));
        }
        updateLabelMap();
    }//GEN-LAST:event_ButtonSaveToMapActionPerformed

    private void ButtonInsertDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertDataMapActionPerformed
        // TODO add your handling code here:
        for (String value : itemsMap.values()) {
            dlm.addElement(value);
        }
    }//GEN-LAST:event_ButtonInsertDataMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListSetMap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonClearAll;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonInsertDataList;
    private javax.swing.JButton ButtonInsertDataMap;
    private javax.swing.JButton ButtonInsertDataSet;
    private javax.swing.JButton ButtonSaveToList;
    private javax.swing.JButton ButtonSaveToMap;
    private javax.swing.JButton ButtonSaveToSet;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JTextField TextFieldItemName;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JLabel jLabelJumlahList;
    private javax.swing.JLabel jLabelJumlahMap;
    private javax.swing.JLabel jLabelJumlahSet;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
